#!/bin/bash
 
#PBS -N Spillway
#PBS -l nodes=1:ppn=10
#PBS -l vmem=48gb
#PBS -l walltime=100:00:00
#PBS -j oe
#PBS -M x.barthelemy@wrl.unsw.edu.au
#PBS -m abe
#PBS -o OUTPUT.txt 

cd $PBS_O_WORKDIR
 
mpirun -np 10 gerris2D Flume2D-Long-N12.gfs
